from infrastructure.solene.profiles.surface_model_profile import SurfaceModelProfile

AZAM_PROFILE = SurfaceModelProfile(
    name="azam",
    meteo_sol_defaults={
        "lambda_sol": 1.3,
        "cp_sol": 1200,
        "rho_sol": 1760,
        "z_ref": 2.0,
        "i_jour": 196,
        "i_jour_ref": 1,
        "moy_Tair": 13.5,
        "max_Tair": 28.5,
        "min_Tair": 1.4,
    },
    carac_face=(
        "albedo",
        "transmittance",
        "transmittance_bat",
        "emissivite",
        "h_int",
        "Tfix",
        "Tint",
        "no_paroi",
        "no_paroi_tr",
        "no_classe",
    ),
    carac_triangle=(
        "surface",
        "ffIn",
        "ffOut",
        "ffSky",
        "evaporation",
        "niveau",
        "entree_air",
        "Ca",
        "Cf",
        "h_pa",
        "h_ainf",
        "v",
        "LAI",
        "h_eau_sol",
        "dt_arrosage_sol",
    ),
    variables_clo=(
        "flux_sol_direct",
        "flux_sol_diffus",
        "flux_sol_total",
        "ecl_inc_direct",
        "ecl_inc_diffus",
        "ecl_inc_total",
        "ecl_ref_direct",
        "ecl_ref_diffus",
        "ecl_ref_total",
        "ecl_abs_direct",
        "ecl_abs_diffus",
        "ecl_abs_total",
        "ecl_diffus",
    ),
    variables_glo=(
        "GLO_Ciel_Net",
        "GLO_Scene_Net",
        "GLO_Total_Net",
        "flux_latent",
        "flux_eau",
        "flux_rad_arbre",
        "humidite_relative",
        "flux_convectif",
    ),
    variables_transient=(
        "Tse",
        "Tn1",
        "Tn2",
        "Tn3",
        "Ta",
        "Tse_veg",
        "Tnoeud",
        "Tinit",
        "hc",
        "Tair",
        "HR",
        "TN3",
        "TN4",
        "TN5",
        "TN6",
        "TN7",
        "TN8",
        "TN9",
        "TN10",
        "TN11",
        "TN12",
        "TN13",
        "TN14",
        "TN15",
        "TN16",
        "TN17",
        "TN18",
        "TN19",
        "TN20",
        "TN21",
        "h_eau_sol_tot",
    ),
    variables_comfort=(
        "flux_sol_direct",
        "flux_sol_diffus",
        "albedo",
        "vitesse_air",
        "temperature_air",
        "MRT",
    ),
    default_time_step_s=900,
    include_ecl_inc_tot = True,
    enable_tp_outputs=False,
    enable_water_descriptors=True,
    enable_extra_transient_nodes=True,
    enable_irrigation_descriptors=True,
    enable_water_flux_outputs=True,
)