from infrastructure.solene.profiles.surface_model_profile import SurfaceModelProfile

BB5_PROFILE = SurfaceModelProfile(
    name="bb5",
    meteo_sol_defaults={
        "lambda_sol": 0.7,
        "cp_sol": 900,
        "rho_sol": 1600,
        "z_ref": 2.0,
        "i_jour": 196,
        "i_jour_ref": 1,
        "moy_Tair": 13.5,
        "max_Tair": 23.8,
        "min_Tair": 1.4,
    },
    carac_face=(
        "albedo",
        "transmittance",
        "transmittance_bat",
        "emissivite",
        "h_int",
        "Tfix",
        "Tint",
        "no_paroi",
        "no_paroi_tr",
        "no_classe",
    ),
    carac_triangle=(
        "surface",
        "ffIn",
        "ffOut",
        "ffSky",
        "evaporation",
        "niveau",
        "entree_air",
        "Ca",
        "Cf",
        "h_pa",
        "h_ainf",
        "v",
        "LAI",
    ),
    variables_clo=(
        "flux_sol_direct",
        "flux_sol_diffus",
        "flux_sol_total",
        "ecl_inc_direct",
        "ecl_inc_diffus",
        "ecl_inc_total",
        "ecl_ref_direct",
        "ecl_ref_diffus",
        "ecl_ref_total",
        "ecl_abs_direct",
        "ecl_abs_diffus",
        "ecl_abs_total",
        "ecl_diffus",
    ),
    variables_glo=(
        "GLO_Ciel_Net",
        "GLO_Scene_Net",
        "GLO_Total_Net",
        "flux_latent",
        "flux_rad_arbre",
        "humidite_relative",
        "flux_convectif",
    ),
    variables_transient=(
        "Tse",
        "Tp1",
        "Tp2",
        "Tn1",
        "Tn2",
        "Tn3",
        "Ta",
        "Tse_veg",
        "Tnoeud",
        "Tinit",
        "hc",
        "Tair",
        "HR",
    ),
    variables_comfort=(
        "flux_sol_direct",
        "flux_sol_diffus",
        "albedo",
        "vitesse_air",
        "temperature_air",
        "MRT",
    ),
    default_time_step_s=3600,
    include_ecl_inc_tot = False,
    enable_tp_outputs=True,
    enable_water_descriptors=False,
    enable_extra_transient_nodes=False,
    enable_irrigation_descriptors=False,
    enable_water_flux_outputs=False,
)